baseurl = "/"
languageCode = "ja"
title = "しいたけ日誌"
theme = "hugo-grapes"
enableEmoji = true

[permalinks]
  post = "/post/:slug/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post"
    weight = 20

[params]
avatar = "img/grapes.svg"
